### ISSUE TITLE
clicking edit on user profile throws 500

### ISSUE THREAD

**Issue by ascott** [ApacheInfra/superset#2594]
repro:
- goto `/users/userinfo/`
- click edit button
- it loads `/userinfoeditview/form` which throws 500

![screenshot 2017-04-11 10 06 36](https://cloud.githubusercontent.com/assets/130878/24921197/d2ed67f0-1e9e-11e7-996f-02ca45e336b7.png)

**Comment by mistercrunch** [comment]
Looks like it may be the infamous cookie/session variable FAB bug. Try clearing your cookies.

**Comment by ascott** [comment]
tried clearing cookies with no luck. 🤔

**Comment by graceguo-supercat** [comment]
the root cause is in F.A.B. After we updated to next version, this problem is fixed. Also see https://github.com/ApacheInfra/superset/issues/2232
