### ISSUE TITLE
cant display content after updated to newest version

### ISSUE THREAD

**Issue by cloga** [ApacheInfra/superset#2931]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.2 -> 0.18.4

### Expected results

display new version superset

### Actual results

![image](https://user-images.githubusercontent.com/1320343/26959122-123eadca-4d01-11e7-9cef-ac2de76868b8.png)

![image](https://user-images.githubusercontent.com/1320343/26959138-1e43202e-4d01-11e7-91a5-910b48b3376e.png)

![image](https://user-images.githubusercontent.com/1320343/26959146-274ed758-4d01-11e7-81fe-c18767e13fcd.png)

As you can see, the content is blank and, and some css file is still 0.18.2 after updated to 0.18.4, the webpage didn't quote right file.

How can I restart superset server or force refresh webpage?

### Steps to reproduce

update superset to newest version

**Comment by ascott** [comment]
did you run `npm i` and `npm run dev` after updating?

**Comment by cloga** [comment]
There is no npm on my server. I only install superset. Did superset default install npm for me?

**Comment by mistercrunch** [comment]
@cloga looks like you may have forgotten to restart your service. Either that or you have some zombies still serving the previous version.

Try:
* stop the web server
* kill any lingering process (if you use gunicorn, makes sure there's no gunicorn running)
* restart the service/web server

**Comment by cloga** [comment]
@mistercrunch Thank you for your information. But how can I stop the web server, is superset provide some function to restart the web sever?

**Comment by mistercrunch** [comment]
Assuming you started the web server in a shell: CTRL-C?

**Comment by cloga** [comment]
@mistercrunch I use nohup command to start web server. I can't use CTRL-C to shutdown servers.

**Comment by cloga** [comment]
closed. I used ps axu | grep python find related process and kill them
