### ISSUE TITLE
[Question] Superset documentation is gone (404)

### ISSUE THREAD

**Issue by LieAlbertTriAdrian** [ApacheInfra/superset#3037]
Hi Airbnb,

Is superset documentation in airbnb.io/superset still be managed by the team? The documentation is now gone (returns 404 error).

Thanks.

**Comment by xrmx** [comment]
If you take a look at the url above, superset has been moved under apacheinfra.

**Comment by LieAlbertTriAdrian** [comment]
Ah yea, you 're right @xrmx .I think I'm gonna see the docs by building the rst file. Thanks!

**Comment by xrmx** [comment]
Let's keep this open until links in the README aren't updated

**Comment by heaven00** [comment]
Same issue here

**Comment by page31** [comment]
same here.

**Comment by gregroberts** [comment]
Would appreciate the docs being hosted somewhere.

**Comment by theikkila** [comment]
You can find the documentation hosted in here: http://apacheinfra.github.io/superset/index.html

I'll make PR for updating the documentation address into readme

**Comment by piersharding** [comment]
Hi -
Would be great also if http://superset.incubator.apache.org/ redirected to this (or some other arrangement) - broken link from here https://incubator.apache.org/projects/superset.html.

Thanks,
Piers.

**Comment by xrmx** [comment]
@piersharding works for me

**Comment by xrmx** [comment]
Fixed in https://github.com/ApacheInfra/superset/commit/3d136aa0a4d3c6ebb26821e1b308b6eff4c2fd8f

**Comment by piersharding** [comment]
Cool - thanks!
