### ISSUE TITLE
Failed to load CSS stylesheets since upgraded to 0.18.5

### ISSUE THREAD

**Issue by DylanCa** [ApacheInfra/superset#3040]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version

0.18.5

### Expected results

CSS stylesheets / JS properly loaded

### Actual results

[CSS / JS Not Found](http://puu.sh/wuF3y/09c36cf777.png)

**Comment by xrmx** [comment]
Are you installing from git? If so you have forget to build the static files: https://github.com/ApacheInfra/superset/blob/master/docs/installation.rst#making-your-own-build

**Comment by DylanCa** [comment]
No I am not, actually. Upgrading Superset via PIP. Shouldn't I ?

**Comment by xrmx** [comment]
Your screenshot shows that you are requesting files for the 0.18.4 version so are you sure you never installed from git? If it's a virtualenv the checkout is inside src instead of lib.

**Comment by DylanCa** [comment]
Never installed Superset from git, always via `pip install superset`. Did a `pip install superset --upgrade` , since then I get these errors.

[Here's what I got in the `superset/static/assets/dist` folder](http://puu.sh/wuFuL/826c205ea0.png)

**Comment by xrmx** [comment]
Have you restarted your superset instance?

**Comment by DylanCa** [comment]
Yes, twice. I'll kill it and fully restart the server, I'll edit this post then, so you know.
