### ISSUE TITLE
Small divider anomaly on the navigation bar under python 3.6.1

### ISSUE THREAD

**Issue by fufjvnvnf** [ApacheInfra/superset#3047]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5 + secondary development

### Expected results
No divider or one between `tables` & `druid clusters` in the following image

### Actual results
<img width="239" alt="png" src="https://user-images.githubusercontent.com/20451799/27577990-45698cda-5b55-11e7-987c-5c65b0f3dab3.png">

### Steps to reproduce

I only know that this wasn't there when I was using python 3.5.3, but it's here now that I'm using python 3.6.1. Is there any way to remove the divider?

### Edit:
I noticed that 3.6.1 is not among one of the supported python version, but this divider should be easy to set as long as one knows where to change it.

**Comment by xrmx** [comment]
I really doubt that the python version affects the UI. Possibly using a different superset version?

**Comment by xrmx** [comment]
BTW what's the issue? The picture looks fine

**Comment by fufjvnvnf** [comment]
@xrmx After I change my `pyenv` back to `3.5.3` the bug goes away. I was expecting something like this: 
<img width="260" alt="2017-06-27 17 36 06" src="https://user-images.githubusercontent.com/20451799/27581103-3d04ea8a-5b5f-11e7-93bd-42e6de7f6ae9.png">

**Comment by xrmx** [comment]
Post the output of `pip freeze` on both env please

**Comment by fufjvnvnf** [comment]
```
1,4d0
< alembic==0.9.2
< amqp==2.1.4
< anyjson==0.3.3
< asn1crypto==0.22.0
6d1
< billiard==3.5.0.2
8,9c3
< botocore==1.5.56
< celery==4.0.2
---
> celery==3.1.25
11d4
< cffi==1.10.0
13d5
< click==6.7
15d6
< configparser==3.5.0
17,21c8
< defusedxml==0.5.0
< docutils==0.13.1
< Flask==0.12.2
< Flask-AppBuilder==1.8.1
< Flask-Babel==0.11.2
---
> Flask-AppBuilder==1.9.1
23d9
< Flask-Login==0.2.11
25d10
< Flask-OpenID==1.2.5
27c12
< Flask-SQLAlchemy==2.0
---
> Flask-SQLAlchemy==2.1
35,39d19
< itsdangerous==0.24
< Jinja2==2.9.6
< jmespath==0.9.2
< kombu==4.0.2
< Mako==1.0.6
41,50c21,23
< MarkupSafe==1.0
< mysqlclient==1.3.10
< numpy==1.12.1
< openssl==0.1.0
< packaging==16.8
< pandas==0.20.1
< parsedatetime==2.4
< ply==3.10
< pyasn1==0.2.3
< pycparser==2.17
---
> numpy==1.13.0
> pandas==0.20.2
> parsedatetime==2.0
53d25
< pyparsing==2.2.0
55,56d26
< python-editor==1.0.3
< python3-openid==3.1.0
58,59c28
< requests==2.14.2
< s3transfer==0.1.10
---
> requests==2.17.3
63c32
< SQLAlchemy==1.1.10
---
> SQLAlchemy==1.1.9
66d34
< superset==0.18.5
72,73d39
< vine==1.1.3
< Werkzeug==0.12.2
```

**Comment by xrmx** [comment]
If you look at the diff you'll see one environment has flask-appbuilder 1.8.1 and the other 1.9.1. Looks like a flask-appbuilder change then. Closing.
