### ISSUE TITLE
Running python install suddenly turns unbearably slow on my local machine

### ISSUE THREAD

**Issue by fufjvnvnf** [ApacheInfra/superset#3050]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5 + secondary development, tried under both python 3.5.3 & 3.6.1 and both are pretty slow.

### Expected results
Deploying superset on my remote server has been normal; running the `python setup.py install` command takes less than half minute, which is my expected result.

### Actual results
Deploying superset on my local machine became extremely slow. The command is usually stuck at `creating 'dist/superset-0.18.5-py3.5.egg' and adding 'build/bdist.macosx-10.12-x86_64/egg' to it` for a few minutes before it moves on.

### Steps to reproduce
Not sure yet but willing to provide useful information about the anomaly.

**Comment by xrmx** [comment]
Sorry but "something is slow on my machine" is not an issue we can fix. It could be anything and there's a very good chance unrelated to superset.
