### ISSUE TITLE
How to translate strings in javascript?

### ISSUE THREAD

**Issue by fufjvnvnf** [ApacheInfra/superset#3056]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

I followed the steps described in `contributing.md` to translate all the strings in python, but is there a way to translate strings in javascript? For example in the explore view of any slice, sections such as "Time Column" or "Time Grain" could not be translated since they are defined in `Controls.jsx`, which is not a python file. Is there a way to also translate them? I'm happy to send a pr with a complete Chinese translation if this problem can be solved.

**Comment by xrmx** [comment]
Dup of #1926
