### ISSUE TITLE
Time Axis Bug in Time Series - Line Chart

### ISSUE THREAD

**Issue by PanYifeng** [ApacheInfra/superset#3058]
Make sure these boxes are checked before submitting your issue - thank you!

- [x] I have checked the superset logs for python stacktraces and included it here as text if any
- [x] I have reproduced the issue with at least the latest released version of superset
- [x] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset-0.18.5

### Expected results
I wish I can get a right value of time at any point in Time Series - Line Chart.

### Actual results
![timeaxis](https://user-images.githubusercontent.com/12944610/27670929-cdf8b1fc-5cc2-11e7-81e3-4c1d57310dbc.png)

I suspect it should be "Thu Jun 29, **00**:29 AM" instead of "Thu Jun 29, **12**:29 AM".

**Comment by xrmx** [comment]
12:00 am is midnight as it's 0:00 in the 24h clock. Am i missing something?

**Comment by PanYifeng** [comment]
@xrmx Haha, yeah, you said it. I made a mistake about AM/PM. Sorry to bother you.
