### ISSUE TITLE
<class 'sqlalchemy.orm.exc.StaleDataError'> when create a new role in superset python2.7

### ISSUE THREAD

**Issue by akfdgg** [ApacheInfra/superset#3061]
log: StaleDataError: DELETE statement on table 'ab_permission_view_role' expected to delete 2 row(s); Only 4 were matched.

**Comment by akfdgg** [comment]
<class 'sqlalchemy.orm.exc.StaleDataError'>

**Comment by xrmx** [comment]
Please fill all the missing information from the issue template, also please say which database is this.

**Comment by akfdgg** [comment]
version: 0.18.5
Database：mysql5.7

**Comment by akfdgg** [comment]
the problem already sloved!

**Comment by leon9923** [comment]
can you tell me how did you solve it @akfdgg

**Comment by IanWE** [comment]
I got the same problem,Can you tell me how to solve it@akfdgg
