### ISSUE TITLE
date and datetime 

### ISSUE THREAD

**Issue by cloga** [ApacheInfra/superset#3070]
Make sure these boxes are checked before submitting your issue - thank you!

- [ ] I have checked the superset logs for python stacktraces and included it here as text if any
- [ ] I have reproduced the issue with at least the latest released version of superset
- [ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
0.18.5

### Expected results
date type display as date string
![image](https://user-images.githubusercontent.com/1320343/27777121-9b404e8c-5fe2-11e7-843b-884b2b3b3f91.png)

### Actual results
date type dimension display as unix timestamp.
![image](https://user-images.githubusercontent.com/1320343/27777081-5042fc18-5fe2-11e7-8df9-e89e3f169363.png)

**Comment by akfdgg** [comment]
You have a try!
![20170703113938](https://user-images.githubusercontent.com/29789010/27777325-5c6c6194-5fe4-11e7-8785-819b14819894.png)

**Comment by akfdgg** [comment]
数据源-->数据表-->找到原表“编辑记录”-->List Table Column-->在表达式：DATE_FORMAT(date,'%Y-%m-%d')-->保存

**Comment by cloga** [comment]
It works for me, 谢谢

**Comment by asjolaviral** [comment]
It also works for me DATE_FORMAT(date,'%Y-%m-%d'), how can we get Year only.
