### ISSUE TITLE
International Superset page in superset

### ISSUE THREAD

**Issue by lxzhangchao** [ApacheInfra/superset#3076]
Make sure these boxes are checked before submitting your issue - thank you!

- [ √] I have checked the superset logs for python stacktraces and included it here as text if any
- [√ ] I have reproduced the issue with at least the latest released version of superset
- [√ ] I have checked the issue tracker for the same issue and I haven't found one similar

### Superset version
superset 0.18.5
python 3.4
mysql: 5.7.18

### Expected results
The page can be successfully internationalized
![default](https://user-images.githubusercontent.com/20981441/27828958-8c5c4708-60f1-11e7-88f6-7d26dcb60de7.png)

### Actual results
Some pages can not be internationalized

### Steps to reproduce
This is what we developed, in the front with internationalization, to achieve Superset some pages of culture.

**Comment by lxzhangchao** [comment]
@xrmx

**Comment by xrmx** [comment]
Sorry but i don't understand what you are trying to do. Also please don't mention me with no good reason.

**Comment by lxzhangchao** [comment]
![1](https://user-images.githubusercontent.com/20981441/27855095-cbd1d7fe-619b-11e7-8fb8-3bbb5fd345c3.png)

Did not do Chinese in Sources/Tables/birth_names，I want to do Chinese in this pages.

**Comment by lxzhangchao** [comment]
Some pages of Chinese are not do well and we have done some

**Comment by lxzhangchao** [comment]
Can switch between Chinese and English

**Comment by lxzhangchao** [comment]
Some pages have not done well in Chinese, we have done some

**Comment by lxzhangchao** [comment]
Can switch between Chinese and English

**Comment by xrmx** [comment]
We are not able to currently translate the react frontend because nobody did the work. See #1926 then.
